---
- name: Setting up the application servers
  become: true
  hosts: all

  tasks:
   - name: "Update cache & Full system update"
     apt:
     update_cache: true
     upgrade: dist
     cache_valid_time: 3600
     force_apt_get: true

   - name: install node version 14
     become: true
     shell: curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash - && sudo apt-get install -y nodejs

   - name: clone the app 
     become: true
     shell: curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash - && sudo apt-get install -y nodejs

   - name: Update packages based on package.json to their latest version.
     npm:
     path: /app/location
     state: latest

