---
- name: Setting up the application servers
  become: true
  hosts: all

  tasks:
   - name: "Update cache & Full system update"
     apt:
  update_cache: true
  upgrade: dist
  cache_valid_time: 3600
  force_apt_get: true