---
- name: Setting up the application servers
  become: true
  hosts: all

  tasks:
   - name: "Update cache & Full system update"
     apt:
      update_cache: true
      upgrade: dist
      cache_valid_time: 3600
      force_apt_get: true
  - name: Install the nodejs LTS repos
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
        state: present
        update_cache: yes